### ISSUE TITLE
HelloWorld program in any language !! 

### ISSUE THREAD

**Issue by NEERAJAP2001** [NEERAJAP2001/HelloWorld#1]
Hello !! Folks, THIS repo is  part of Hacktoberfest :  🎁

1. Star the repo
2. Write a HelloWorld program in any language.
3. Name the file as HelloWorld with your extension.
3. THIS IS THE TARGET REPO 
4. You can update the Read.md file If you want to!😊 
5. Wait for it to be merged!! ( I'm mostly online so, sit back and relax 😃)

MAKE SURE THE LANGUAGE YOU'VE CHOSEN IS  NOT THERE IN THE REPO ALREADY!!

ENJOY OPEN SOURCING !! 😃

**Comment by nikhil05-code** [comment]
Please assign it to me.

**Comment by NEERAJAP2001** [comment]
bro! just go ahead!! anyone can solve it. ( NO ASSIGNING )

**Comment by yabaa** [comment]
Hey @NEERAJAP2001 , looks like your project is not eligible for the hacktoberfest event, I am seeing this for my 2 merged PR:

Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by NEERAJAP2001** [comment]
yeah, @yabaa  I've changed the settings now  !!

**Comment by drishyadamodaran** [comment]
@NEERAJAP2001 check mine

**Comment by NEERAJAP2001** [comment]
Yeah!! merged  😊!!

**Comment by RahulRS246** [comment]
i would like to do it
